# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['create-*.Rmd', 'source-files/**']

name: render-litr

jobs:
  render-litr:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - name: Install libcurl to avoid error with curl R package
        run: sudo apt-get install libcurl4-openssl-dev

      - name: Install litr and dependencies
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown", "remotes"))'
          Rscript -e 'remotes::install_github("jacobbien/litr-project@*release", subdir = "litr")'

      - name: Render Rmarkdown files and Commit Results
        run: |
          TOP_LEVEL_RMD=($(find . -maxdepth 1 -type f  -regex '.*create-.*\.[Rr][Mm][Dd]' -exec basename {} \;))
          echo "$TOP_LEVEL_RMD"
          RMD_FILENAME=${TOP_LEVEL_RMD/.*/}
          PKG_NAME=$(echo "$RMD_FILENAME" | rev | cut -d- -f1 | rev)
          echo "$PKG_NAME"
          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "$TOP_LEVEL_RMD"))
          echo "$RMD_PATH"
          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) litr::render(f)' ${RMD_PATH[*]}
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit "${RMD_FILENAME}.html" "${PKG_NAME}/"  -m 'Re-build Litr file and package' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
